// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError('Platform not supported');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw6CA5xZl20QltJjI-QgPHlnaErj3-Gpo',
    appId: '1:845776305709:web:83ddbe48c9d89b56ab42a4',
    messagingSenderId: '845776305709',
    projectId: 'xcorerestaurant',
    authDomain: 'xcorerestaurant.firebaseapp.com',
    storageBucket: 'xcorerestaurant.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw6CA5xZl20QltJjI-QgPHlnaErj3-Gpo',
    appId: '1:845776305709:android:ede915683ed459a0ab42a4',
    messagingSenderId: '845776305709',
    projectId: 'xcorerestaurant',
    storageBucket: 'xcorerestaurant.firebasestorage.app',
  );
}